#
# Executes commands at login pre-zshrc
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR}/init.zsh" ]]; then
  source "${ZDOTDIR}/init.zsh"
fi
#
# Customize to your needs...

alias dmesg="dmesg --human"
alias vim="nvim"
