#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
#
# Customize to your needs...

# export PATH=$PATH:/home/eleanor/Documents/Computer/Phone/android-sdk-linux/platform-tools
# export _JAVA_AWT_WM_NONREPARENTING=1
# export PYTHONPATH="$PYTHONPATH:$HOME/Dissent/git/python/"
# export GOROOT=/usr/local/go
# export GOPATH=$HOME/go
# export GOBIN=$GOPATH/bin
# export PATH=$PATH:/usr/local/go/bin

alias joern='java -jar /home/eleanor/Documents/joern/bin/joern.jar'
